### ISSUE TITLE
A Unicode-related issue in the Grammar class

### ISSUE THREAD

**Issue by vkazanov** [aparrish/pytracery#29]
I use unicode non-terminals in my grammar, and whenever I make a mistake in my rules - pytracery crashes with the following error:

``` 
File "/my/project/path/.env/local/lib/python2.7/site-packages/tracery/__init__.py", line 264, in select_rule
    return "((" + str(key) + "))"
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
```

This is mostly because `str` is used where just using the key string as is would be enough.

PS A great port of Tracery, BTW! Thanks!

**Comment by vkazanov** [comment]
BTW, is there a way to extract the errors..? I found no clear way of doing that in the code itself.

**Comment by hugovk** [comment]
Do you have a small example grammar that reproduces the problem?

**Comment by vkazanov** [comment]
Yes, sure. It's not only a grammar, but a complete file with printing the results:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals

import tracery

rules = {
    'корень': '#правило# #пправило#',
    'правило': 'первое',
    ' пправило': 'второе',

}


def main():
    grammar = tracery.Grammar(rules)
    output = grammar.flatten("#корень#")
    print(output)
    print("test")

if __name__ == '__main__':
    main()

```

Notice the Unicode strings in the grammar rules.

**Comment by hugovk** [comment]
The root cause is trying to do `str(unicode("пправило"))`, which isn't a problem in Python 3. 

Anyway, here's a PR with a unit test: https://github.com/aparrish/pytracery/pull/30.

**Comment by hugovk** [comment]
> BTW, is there a way to extract the errors..? I found no clear way of doing that in the code itself.

Do you mean a way to identify which line in the grammar causes the problem? 

With this fix (or with Python 3, or with "simple" Unicode), it'll output `первое ((пправило))`, so you know there's a problem with the `пправило` rule.

**Comment by vkazanov** [comment]
I noticed in the Grammar there's a self.errors = [] property which seems to be containing all the errors collected during the flattening but there's no way of getting that information and the property becomes an empty array by the end of the procedure.

E.g., in the code near the fix there's `errors.append("No symbol for " + key)`. It seems that the code is supposed to collect the errors and somehow present them later.

**Comment by hugovk** [comment]
You can access those errors: 
```python
    grammar = tracery.Grammar(rules)
    output = grammar.flatten("#корень#")
    print(grammar.errors)
    print(output)
```

But you're right, it's `[]`.

That's because the error message is appended to a local `errors` list, but then discarded in the else case:

```python
    def select_rule(self, key, node, errors):
        if key in self.symbols:
            return self.symbols[key].select_rule(node, errors)
        else:
            errors.append("No symbol for " + str(key))
            return "((" + str(key) + "))"
```

There may be other places where a local `errors` is used and discarded, but I'll just fix this one in that PR.

**Comment by vkazanov** [comment]
Great! Thanks a lot!
