### ISSUE TITLE
Extending modifiers to make use of inflect.py

### ISSUE THREAD

**Issue by psychemedia** [aparrish/pytracery#32]
One of the packages I use for generating text from data is [`inflect.py`](https://github.com/pwdyson/inflect.py).

I made a start at incorporating `inflect.py` mappings into the *base_english* modifiers [here](https://github.com/psychemedia/pytracery/commit/d5f870101a8d071a500cb2d5b21475ff451b5629).

It strikes me it would be nice to be able to specify lots of different modifier packs, and then apply them as required. At the moment, I think a formulation along lines of:

```
grammar.add_modifiers(base_english)
grammar.add_modifiers(custom_english)
```
would generate strings that were not as desired?

Instead, maybe need a way to register different modifiers and construct a single modifier set from them, albeit at the risk of replacing commonly named modifiers across the different packs (eg *inflect.py* has an `a` modification that overrides the `base_english` one) unless different namespaces were invoked?

**Comment by aparrish** [comment]
I'm happy with the way the `add_modifiers` method is engineered at the moment—you just give it a dictionary that maps modifiers to functions. Easy peasy. I do really love the work you're doing to use `inflect.py`'s functions to augment the base modifiers! I think I'd be inclined to accept a PR that works essentially as you have it modified in your fork right now, with a second dictionary of modifiers defined in the module that can then be passed to the `add_modifiers` method (while maintaining the original `base_english` modifiers for compatibility).

I don't really favor a registration approach (and I *especially* don't want to add the concept of namespaces!)—it feels over-engineered. If advanced users want to make a custom set of modifiers, they can construct the dictionary mapping modifier names to functions in their own code.
