### ISSUE TITLE
Conditional actions in stories

### ISSUE THREAD

**Issue by psychemedia** [aparrish/pytracery#37]
I'm struggling with thinking of ways of taking a conditional action based on the value of a particular parameter.

I've come up with a Frankenstein rule:

```
def branch(text, *params):
    if text==params[0].strip(): 
        ans = params[1].strip()
    else:
        ans = params[2].strip()
    return '[answer:#{}#]'.format(ans)

pytracery_logic = {
    'branch':branch,
}

rules={'origin':'Logical test:[branch:#condition#]#branch# Testing #value# gives: #answer#',
       'condition': '#value.branch(VeryTrue, answer1, answer2)#',
    'answer1':'This is true...',
    'answer2':'This is false...',
    'answer3':'nope',
    'answer':'answer3'
}

grammar = tracery.Grammar(rules)
grammar.add_modifiers(pytracery_logic)

print(grammar.flatten("[value:VeryTrue]#origin#"))
>Logical test: Testing VeryTrue gives: This is true...

print(grammar.flatten("[value:notTrue]#origin#"))
>Logical test: Testing notTrue gives: This is false...
```

but was wondering if there's a more idiomatic *pytracery* way of doing it?

(I appreciate this is a bit offbeat for the stories I imagine tracery was originally created to support; my interest is in using it to generate narratives from data sets.)

**Comment by psychemedia** [comment]
It also strikes me we can now do a loop, too:

```
def repeat(text, *params):
    if int(text) > 0:
        return '[i:{i}]'.format(i=str(int(text)-1))
    return '[until:#{}#]'.format(params[0].strip())

pytracery_logic = {
    'branch':branch,
    'repeat': repeat
}

rules = {'origin': '[branch:#i.repeat(end)#]#branch# #until#',
         'until':'#looper##origin#',
         'looper':'Count is at #i#\n',
         'end':'All done'
        }

#something like: here we go: one, two, three. Done
grammar = tracery.Grammar(rules)
grammar.add_modifiers(pytracery_logic)
print(grammar.flatten("[i:4]#origin#"))

Count is at 3
 Count is at 2
 Count is at 1
 Count is at 0
 All done
```

**Comment by aparrish** [comment]
there's really no "pytracery" way of doing it. I tend to rely more on Python for logic, isolating the text generation/template expansion parts of the code as much as possible, and sometimes building grammars procedurally when necessary. but I think your approaches here are sound. as I've mentioned in another thread, I'm unlikely to merge custom modifiers or other changes to Tracery syntax into this repository, but please feel free to develop and distribute custom modifiers on your own!
